// <auto-generated />
namespace SalesmanProductManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newtwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtwo));
        
        string IMigrationMetadata.Id
        {
            get { return "202105122202076_newtwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
